# Copyright 2018 M. Riechert and D. Meyer. Licensed under the MIT License.

image: Visual Studio 2017 # See https://www.appveyor.com/docs/build-environment/

clone_depth: 50

environment:
  global:
    WRF_REPO: WRF-CMake/WRF
    WRF_COMMIT: wrf-cmake
    
  matrix:
    - BUILD_TYPE: Release
      MODE: serial
      NESTING: basic
      GRIB1: 0
      GRIB2: 1

    - BUILD_TYPE: Release
      MODE: dmpar
      NESTING: basic
      GRIB1: 0
      GRIB2: 1

install:
  - cd ..
  - git clone --depth=100 --no-single-branch git@github.com:%WRF_REPO%.git WRF
  - cd WRF
  - git checkout %WRF_COMMIT%
  - call .ci\appveyor\setup-dependencies.bat
  - call .ci\appveyor\install-wrf.bat
  - cd %APPVEYOR_BUILD_FOLDER%

build_script:
  - call .ci\appveyor\install-wps.bat

artifacts:
  - path: build/install
    name: WPS