# Copyright 2018 M. Riechert and D. Meyer. Licensed under the MIT License.

language: python
python: "3.6"

env:
  global:
    - WRF_REPO=WRF-CMake/WRF
    - WRF_COMMIT=letmaik/azure-pipelines

jobs:
  include:
    # Make builds

    - stage: build
      os: linux
      dist: trusty
      sudo: required
      env:
        - BUILD_SYSTEM=Make
        - BUILD_TYPE=Debug
        - CC=gcc
        - FC=gfortran
        - MODE=serial

    - stage: build
      os: linux
      dist: trusty
      sudo: required
      env:
        - BUILD_SYSTEM=Make
        - BUILD_TYPE=Debug
        - CC=gcc
        - FC=gfortran
        - MODE=dmpar

    - stage: build
      os: osx
      osx_image: xcode9.2 # https://github.com/travis-ci/travis-ci/issues/9640
      language: generic
      env:
        - BUILD_SYSTEM=Make
        - BUILD_TYPE=Debug
        - CC=gcc-8 # GNU via Homebrew
        - FC=gfortran-8
        - MODE=serial

    - stage: build
      os: osx
      osx_image: xcode9.2 # https://github.com/travis-ci/travis-ci/issues/9640
      language: generic
      env:
        - BUILD_SYSTEM=Make
        - BUILD_TYPE=Debug
        - CC=gcc-8 # GNU via Homebrew
        - FC=gfortran-8
        - MODE=dmpar

    # CMake builds

    - stage: build
      os: linux
      dist: trusty
      sudo: required # Need sudo to install netcdf via apt as not whitelisted 
      env:
        - BUILD_SYSTEM=CMake
        - BUILD_TYPE=Debug
        - CC=gcc
        - FC=gfortran
        - GRIB1=0
        - GRIB2=1
        - MODE=serial
        - NESTING=basic

    - stage: build
      os: linux
      dist: trusty
      sudo: required
      env:
        - BUILD_SYSTEM=CMake
        - BUILD_TYPE=Debug
        - CC=gcc
        - FC=gfortran
        - GRIB1=1
        - GRIB2=0
        - MODE=dm_sm
        - NESTING=basic

    - stage: build
      os: osx
      osx_image: xcode9.2 # https://github.com/travis-ci/travis-ci/issues/9640
      language: generic
      env:
        - BUILD_SYSTEM=CMake
        - BUILD_TYPE=Debug
        - CC=gcc-8 # GNU via Homebrew
        - FC=gfortran-8
        - GRIB1=1
        - GRIB2=1
        - MODE=serial
        - NESTING=basic

    - stage: build
      os: osx
      osx_image: xcode9.2 # https://github.com/travis-ci/travis-ci/issues/9640
      language: generic
      env:
        - BUILD_SYSTEM=CMake
        - BUILD_TYPE=Debug
        - CC=gcc-8 # GNU via Homebrew
        - FC=gfortran-8
        - GRIB1=1
        - GRIB2=1
        - MODE=dmpar
        - NESTING=basic

before_install:
  - .ci/unix/dump-vm-specs.sh
  - pushd ..
  - git clone --depth=100 --no-single-branch https://github.com/$WRF_REPO.git WRF
  - cd WRF
  - git checkout $WRF_COMMIT
  - .ci/unix/setup-dependencies.sh
  - .ci/unix/install-wrf.sh
  - popd

install:
  - .ci/unix/install-wps.sh

script: skip
