trigger: none

variables:
  WRF_REPO: WRF-CMake/WRF
  WRF_COMMIT: letmaik/azure-pipelines
  WATS_REPO: WRF-CMake/wats
  WATS_BRANCH: master
  WATS_MODE: wps

jobs:
# TODO CC/FC are not used for Make builds

- template: .ci/azure/wats_pkg.yml
  parameters:
    OS_NAME: Linux
    BUILD_SYSTEM: Make
    BUILD_TYPE: Debug
    CC: gcc
    FC: gfortran
    MODE: serial

      