# Runs on commits to any branch except wps-cmake.
trigger:
  branches:
    include:
    - '*'
    exclude:
    - wps-cmake
  paths:
    exclude:
    - 'README*'
pr: none

jobs:
- template: .ci/azure-pipelines/matrix.yml
  parameters:
    WATS_RUN: false