# WRF-CMake (https://github.com/WRF-CMake/wps).
# Copyright 2019 M. Riechert and D. Meyer. Licensed under the MIT License.

# Runs on commits to the wps-cmake branch and PRs.
trigger:
  branches:
    include:
    - wps-cmake
  paths:
    exclude:
    - 'README*'

# Run every week even if there are no code changes.
# Catches any problems due to new dependency versions from package managers.
schedules:
- cron: "0 0 * * Thu"
  displayName: Weekly build
  branches:
    include: [ wps-cmake ]
  always: true

jobs:
- template: .ci/azure-pipelines/matrix.yml
  parameters:
    WATS_RUN: true
