# WRF-CMake (https://github.com/WRF-CMake/wps).
# Copyright 2019 M. Riechert and D. Meyer. Licensed under the MIT License.

# Runs on commits to any branch except wps-cmake.
trigger:
  branches:
    include:
    - '*'
    exclude:
    - wps-cmake
  paths:
    exclude:
    - 'README*'
pr: none

jobs:
- template: .ci/azure-pipelines/matrix.yml
  parameters:
    WATS_RUN: false