# WRF-CMake (https://github.com/WRF-CMake/wps).
# Copyright 2019 M. Riechert and D. Meyer. Licensed under the MIT License.

steps:
- bash: $(run) .ci/unix/use-conda.sh
  displayName: Enable Conda

- bash: $(run) .ci/unix/install-wats.sh
  displayName: Install WATS

- bash: $(run) .ci/unix/run-wats.sh
  displayName: Run WATS

- task: PublishBuildArtifacts@1
  displayName: Store WATS outputs
  inputs:
    pathtoPublish: wats_work/output
    artifactName: wats_$(OS_NAME)_$(BUILD_SYSTEM)_$(BUILD_TYPE)_$(MODE)
