# WRF-CMake (https://github.com/WRF-CMake/wps).
# Copyright 2019 M. Riechert and D. Meyer. Licensed under the MIT License.

steps:
- bash: .ci/unix/use-conda.sh
  displayName: Enable Conda

- bash: |
    set -ex
    mkdir wats && cd wats
    curl -L --retry 3 https://github.com/$WATS_REPO/archive/$WATS_BRANCH.tar.gz | tar xz --strip-components=1
    conda env update -n base -f environment.yml
  displayName: Install WATS

- bash: |
    set -ex
    if [[ $MODE == dm* ]]; then mpi_flag="--mpi"; fi
    if [[ $BUILD_SYSTEM == "CMake" ]]; then dir_suffix="build/install"; fi
    python wats/wats/main.py run --mode $WATS_MODE --wrf-dir ../WRF/$dir_suffix --wps-dir ./$dir_suffix --work-dir wats_work $mpi_flag
  displayName: Run WATS

- task: PublishBuildArtifacts@1
  displayName: Store WATS outputs
  inputs:
    pathtoPublish: wats_work/output
    artifactName: wats_$(OS_NAME)_$(BUILD_SYSTEM)_$(BUILD_TYPE)_$(MODE)
