# WRF-CMake (https://github.com/WRF-CMake/wps).
# Copyright 2019 M. Riechert and D. Meyer. Licensed under the MIT License.

jobs:
- job: ${{ parameters.OS_NAME }}_${{ parameters.BUILD_SYSTEM }}_${{ parameters.BUILD_TYPE }}_${{ parameters.MODE }}
  displayName: '${{ parameters.OS_NAME }} ${{ parameters.BUILD_SYSTEM }}: ${{ parameters.BUILD_TYPE }}, ${{ parameters.MODE }}'

  timeoutInMinutes: 0

  pool:
    vmImage: windows-latest

  variables:
    ${{ insert }}: ${{ parameters }}

  steps:
  - pwsh: .ci\windows\dump-vm-specs.ps1
    displayName: Dump VM specs

  - script: set
    displayName: Dump environment variables

  - script: |
      cd ..
      git clone --depth=100 --no-single-branch https://github.com/%WRF_REPO%.git WRF
      cd WRF
      git checkout %WRF_COMMIT%
      git log --oneline -n 1
    displayName: Download WRF

  - task: BatchScript@1
    displayName: Setup dependencies
    inputs:
      filename: ..\WRF\.ci\windows\setup-dependencies.bat
      modifyEnvironment: true

  - script: call ..\WRF\.ci\windows\install-wrf.bat
    displayName: Install WRF

  - script: call .ci\windows\install-wps.bat
    displayName: Install WPS

  - ${{ if eq(parameters.WATS_RUN, 'true') }}:
    - template: wats_run.yml

  - ${{ if eq(parameters.RELEASE, 'true') }}:
    - template: release.yml
      parameters:
        ${{ insert }}: ${{ parameters }}