jobs:
- job: ${{ parameters.OS_NAME }}_${{ parameters.BUILD_SYSTEM }}_${{ parameters.BUILD_TYPE }}_${{ parameters.MODE }}
  displayName: ${{ parameters.OS_NAME }} ${{ parameters.BUILD_SYSTEM }} [${{ parameters.BUILD_TYPE }}, ${{ parameters.MODE }}]

  pool:
    ${{ if eq(parameters.OS_NAME, 'Linux') }}:
      vmImage: ubuntu-16.04
    ${{ if eq(parameters.OS_NAME, 'macOS') }}:
      vmImage: macos-10.13

  variables:
    ${{ each pair in parameters }}:
      ${{ pair.key }}: ${{ pair.value }}

  steps:
  - script: |
      if [[ $OS_NAME == 'macOS' ]]; then
        sw_vers
        top -l 1 -s 0 | grep PhysMem
        sysctl hw
        df -h
      else
        lsb_release -a
        free -m
        lscpu
        df -h --total
      fi
    displayName: Dump VM specs

  - script: printenv
    displayName: Dump environment variables

  - script: |
      set -e
      cd ..
      git clone --depth=100 --no-single-branch https://github.com/$WRF_REPO.git WRF
      cd WRF
      git checkout $WRF_COMMIT
      git log --oneline -n 1
    displayName: Download WRF

  - script: ../WRF/.ci/azure/scripts/setup-dependencies.sh
    displayName: Setup dependencies

  - script: ../WRF/.ci/azure/scripts/install-wrf.sh
    displayName: Install WRF

  - script: .ci/azure/scripts/install-wps.sh
    displayName: Install WPS

  - template: .ci/azure/wats_run.yml
