jobs:
- job: ${{ parameters.OS_NAME }}_${{ parameters.BUILD_SYSTEM }}_${{ parameters.BUILD_TYPE }}_${{ parameters.MODE }}
  displayName: '${{ parameters.OS_NAME }} ${{ parameters.BUILD_SYSTEM }}: ${{ parameters.BUILD_TYPE }}, ${{ parameters.MODE }}'

  pool:
    vmImage: vs2017-win2016

  variables:
    ${{ each pair in parameters }}:
      ${{ pair.key }}: ${{ pair.value }}

  steps:
  - pwsh: |
      Get-CimInstance Win32_Processor | Select-Object -Property [a-z]*
      Get-CimInstance Win32_OperatingSystem | Select-Object -Property [a-z]*
      Get-CimInstance Win32_LogicalDisk
    displayName: Dump VM specs

  - script: set
    displayName: Dump environment variables

  # We will install the latest version later on.
  - pwsh: |
      $products = Get-CimInstance -ClassName Win32_Product -Filter "Name like 'Microsoft MPI%'"
      foreach ($p in $products) {
        echo "Uninstalling $($p.Name)"
        Invoke-CimMethod -InputObject $p -MethodName Uninstall
      }
    condition: and(succeeded(), startsWith(variables.MODE, 'dm'))
    displayName: Remove existing MSMPI

  - script: |
      choco install msys2 --params "/InstallDir:c:\msys64"
    displayName: Install MSYS2

  - script: |
      pushd ..
      git clone --depth=100 --no-single-branch https://github.com/%WRF_REPO%.git WRF
      cd WRF
      git checkout %WRF_COMMIT%
      git log --oneline -n 1
    displayName: Download WRF

  - task: BatchScript@1
    displayName: Setup dependencies
    inputs:
      filename: ..\WRF\.ci\appveyor\setup-dependencies.bat
      modifyEnvironment: true

  - script: call ..\WRF\.ci\appveyor\install-wrf.bat
    displayName: Install WRF

  - script: call .ci\appveyor\install-wps.bat
    displayName: Install WPS

  - template: wats_run.yml
